-- CSA Master Pricelist
-- Jalankan seluruh file ini satu kali melalui Supabase SQL Editor.
-- Aman dijalankan ulang: data yang sudah ada tidak dihapus.

begin;

create extension if not exists pgcrypto;

-- Profil pengguna. Akun baru selalu berstatus viewer; admin ditetapkan manual.
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'viewer' check (role in ('viewer', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (user_id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.email))
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_catalog_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = (select auth.uid())
      and role = 'admin'
  );
$$;

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists brands_name_unique_idx
on public.brands (lower(btrim(name)));

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists categories_name_unique_idx
on public.categories (lower(btrim(name)));

-- Satu baris mewakili satu tipe/ukuran utama, misalnya UNO 50x50.
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  legacy_key text unique,
  brand_id bigint references public.brands(id) on delete set null,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  size_label text,
  unit text,
  packaging text,
  tax_note text,
  description text,
  source text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_brand_id_idx on public.products (brand_id);
create index if not exists products_category_id_idx on public.products (category_id);
create index if not exists products_name_idx on public.products (name);
create index if not exists products_active_idx on public.products (is_active);

-- Satu produk boleh memiliki banyak SKU/motif/warna.
create table if not exists public.product_skus (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  code text,
  name text not null,
  description text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, product_id)
);

create unique index if not exists product_skus_product_code_unique_idx
on public.product_skus (product_id, lower(btrim(code)))
where code is not null and btrim(code) <> '';

create index if not exists product_skus_product_id_idx on public.product_skus (product_id);
create index if not exists product_skus_name_idx on public.product_skus (name);

-- Gambar dapat berlaku untuk produk utama atau SKU tertentu.
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  sku_id bigint,
  storage_path text not null unique,
  alt_text text,
  is_primary boolean not null default false,
  sort_order integer not null default 0,
  width integer,
  height integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (sku_id, product_id)
    references public.product_skus(id, product_id)
    on delete cascade,
  check (width is null or width > 0),
  check (height is null or height > 0)
);

create index if not exists product_images_product_id_idx on public.product_images (product_id);
create index if not exists product_images_sku_id_idx on public.product_images (sku_id);

-- Harga dipisah dari produk agar tier minimum order dan promo tidak hilang.
-- sku_id null berarti harga berlaku untuk seluruh SKU pada produk tersebut.
create table if not exists public.price_tiers (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  product_id bigint not null references public.products(id) on delete cascade,
  sku_id bigint,
  list_price numeric(16,2),
  discount_text text,
  net_price numeric(16,2),
  program_price numeric(16,2),
  effective_price numeric(16,2)
    generated always as (coalesce(program_price, net_price, list_price)) stored,
  minimum_order text,
  minimum_quantity numeric(16,3),
  minimum_unit text,
  area text,
  price_per_piece numeric(16,2),
  price_per_sqm numeric(16,2),
  price_per_meter numeric(16,2),
  valid_from date,
  valid_until date,
  promo_valid_until date,
  source text,
  note text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (sku_id, product_id)
    references public.product_skus(id, product_id)
    on delete cascade,
  check (list_price is null or list_price >= 0),
  check (net_price is null or net_price >= 0),
  check (program_price is null or program_price >= 0),
  check (minimum_quantity is null or minimum_quantity >= 0),
  check (valid_until is null or valid_from is null or valid_until >= valid_from)
);

create index if not exists price_tiers_product_id_idx on public.price_tiers (product_id);
create index if not exists price_tiers_sku_id_idx on public.price_tiers (sku_id);
create index if not exists price_tiers_active_idx on public.price_tiers (is_active);
create index if not exists price_tiers_promo_valid_until_idx on public.price_tiers (promo_valid_until);

-- Frontend cukup membaca satu baris ini untuk mengetahui ada data baru.
create table if not exists public.catalog_versions (
  key text primary key,
  version bigint not null default 1 check (version > 0),
  updated_at timestamptz not null default now(),
  note text
);

insert into public.catalog_versions (key, version, note)
values ('catalog', 1, 'inisialisasi katalog supabase')
on conflict (key) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.bump_catalog_version()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.catalog_versions (key, version, updated_at, note)
  values ('catalog', 1, now(), 'katalog diperbarui')
  on conflict (key) do update
  set version = public.catalog_versions.version + 1,
      updated_at = excluded.updated_at,
      note = excluded.note;
  return null;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'profiles', 'brands', 'categories', 'products',
    'product_skus', 'product_images', 'price_tiers'
  ] loop
    execute format(
      'drop trigger if exists %I on public.%I',
      'set_' || table_name || '_updated_at',
      table_name
    );
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.set_updated_at()',
      'set_' || table_name || '_updated_at',
      table_name
    );
  end loop;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array['brands', 'categories', 'products', 'product_skus', 'product_images', 'price_tiers'] loop
    execute format(
      'drop trigger if exists %I on public.%I',
      'bump_catalog_on_' || table_name,
      table_name
    );
    execute format(
      'create trigger %I after insert or update or delete on public.%I for each statement execute function public.bump_catalog_version()',
      'bump_catalog_on_' || table_name,
      table_name
    );
  end loop;
end;
$$;

alter table public.profiles enable row level security;
alter table public.brands enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_skus enable row level security;
alter table public.product_images enable row level security;
alter table public.price_tiers enable row level security;
alter table public.catalog_versions enable row level security;

drop policy if exists "read own profile" on public.profiles;
create policy "read own profile"
on public.profiles for select to authenticated
using (user_id = (select auth.uid()) or public.is_catalog_admin());

drop policy if exists "admins manage profiles" on public.profiles;
create policy "admins manage profiles"
on public.profiles for all to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

drop policy if exists "public read brands" on public.brands;
create policy "public read brands"
on public.brands for select to anon, authenticated using (true);

drop policy if exists "public read categories" on public.categories;
create policy "public read categories"
on public.categories for select to anon, authenticated using (true);

drop policy if exists "public read active products" on public.products;
create policy "public read active products"
on public.products for select to anon, authenticated using (is_active);

drop policy if exists "public read active skus" on public.product_skus;
create policy "public read active skus"
on public.product_skus for select to anon, authenticated
using (
  is_active and exists (
    select 1 from public.products p
    where p.id = product_id and p.is_active
  )
);

drop policy if exists "public read active images" on public.product_images;
create policy "public read active images"
on public.product_images for select to anon, authenticated
using (
  exists (
    select 1 from public.products p
    where p.id = product_id and p.is_active
  )
);

drop policy if exists "public read active prices" on public.price_tiers;
create policy "public read active prices"
on public.price_tiers for select to anon, authenticated
using (
  is_active and exists (
    select 1 from public.products p
    where p.id = product_id and p.is_active
  )
);

drop policy if exists "public read catalog version" on public.catalog_versions;
create policy "public read catalog version"
on public.catalog_versions for select to anon, authenticated using (true);

do $$
declare
  table_name text;
begin
  foreach table_name in array array['brands', 'categories', 'products', 'product_skus', 'product_images', 'price_tiers', 'catalog_versions'] loop
    execute format('drop policy if exists "admins manage %s" on public.%I', table_name, table_name);
    execute format(
      'create policy "admins manage %s" on public.%I for all to authenticated using (public.is_catalog_admin()) with check (public.is_catalog_admin())',
      table_name,
      table_name
    );
  end loop;
end;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.brands, public.categories, public.products,
  public.product_skus, public.product_images, public.price_tiers,
  public.catalog_versions to anon, authenticated;
grant select on public.profiles to authenticated;
grant insert, update, delete on public.profiles, public.brands, public.categories,
  public.products, public.product_skus, public.product_images,
  public.price_tiers, public.catalog_versions to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_catalog_admin() to anon, authenticated;

-- Bucket publik hanya untuk menampilkan gambar. Upload/hapus tetap khusus admin.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public read product images bucket" on storage.objects;
create policy "public read product images bucket"
on storage.objects for select to anon, authenticated
using (bucket_id = 'product-images');

drop policy if exists "admins upload product images" on storage.objects;
create policy "admins upload product images"
on storage.objects for insert to authenticated
with check (bucket_id = 'product-images' and public.is_catalog_admin());

drop policy if exists "admins update product images" on storage.objects;
create policy "admins update product images"
on storage.objects for update to authenticated
using (bucket_id = 'product-images' and public.is_catalog_admin())
with check (bucket_id = 'product-images' and public.is_catalog_admin());

drop policy if exists "admins delete product images" on storage.objects;
create policy "admins delete product images"
on storage.objects for delete to authenticated
using (bucket_id = 'product-images' and public.is_catalog_admin());

commit;
