create table if not exists public.products (
  id bigint primary key,
  brand text,
  category text,
  name text,
  sku text,
  unit text,
  packaging text,
  list_price numeric,
  discount text,
  net_price numeric,
  tax text,
  program_price numeric,
  minimum_order text,
  source text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_brand_idx on public.products (brand);
create index if not exists products_category_idx on public.products (category);
create index if not exists products_sku_idx on public.products (sku);

alter table public.products enable row level security;
create policy "authenticated users can read products"
on public.products for select
to authenticated
using (true);

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  list_price numeric,
  net_price numeric,
  program_price numeric,
  valid_from date not null default current_date,
  valid_until date,
  note text,
  created_at timestamptz not null default now()
);
